Find tile count for each ukeire, add get_placing(), etc.
harphield/riichi-tools-rs pull request #5
Opened 2020-11-08 16:32 UTC by arsdragonfly

Also fixes all warnings, and fixes formatting with `cargo fmt`.

2020-11-08 21:54 UTC, harphield requested changes
Hey, @arsdragonfly ! Thanks for the PR :) I like the change to find_shanten_improving_tiles, it makes sense and gives more info about the hand. One thing I would keep though, is the last part of the returned tuple for the method (total count of improving tiles), so you won't need to always iterate and sum the counts to get that number down the line. What do you think?

2020-11-09 01:00 UTC, arsdragonfly commented
good point! I've added the total ukeire count back.

2020-11-11 21:13 UTC, harphield approved these changes

2020-11-11 21:14 UTC, merged

2020-11-11 22:21 UTC, harphield commented
@arsdragonfly merged and also updated my hand analyzer to show the new numbers (when you hover over the tile https://riichi.harphield.com/tools/hand-analyzer/?hand=258s1779p3668m117z ) :)